project:
  type: website

website:
  navbar:
    background: none
    search: true
    left:
      - text: "Home"
        file: index.qmd
  sidebar:
    style: "docked"
    contents: auto

execute:
  freeze: auto
